### ISSUE TITLE
4.7.1 Non-opioid analgesics - paracetamol. Incorrect dosage information

### ISSUE THREAD

**Issue by drcjar** [nhshackday/mobileformulary#2]
Dose information should begin:
By mouth, 0.5-1g every 4-6 hours to a max of 4g daily;

openbnf.org reads Migraine, 2 capsules at onset of attack, followed by 1 capsule every hour if necessary; max. 5 capsules in 12 hours;childnot recommended

**Comment by davidmiller** [comment]
This is to do with the way the data was initially parsed. 

There are a few problems here, it's more of a rabbit hole than a simple paracetamol issue.

On it though :)

**Comment by davidmiller** [comment]
This was addressed in 62bf426a179218f080f205097a3e53de4b82ec2b 19b72842ca38071043e62c682c448369052f673c 1f82666f07e7c3a97a86c9accb5af3f793935227

These changes have been deployed to OpenBNF.org
