### ISSUE TITLE
Warfarin gives Page Error

### ISSUE THREAD

**Issue by Sinjy** [nhshackday/mobileformulary#6]
Warfarin gives "Error Loading Page" but Warfarin Sodium loads fine.
Via iPhone if that makes a difference.

**Comment by rossjones** [comment]
Warfarin doesn't have a separate page on BNF, just a list of interactions when linked to from Warfarin Sodium (see http://www.medicinescomplete.com/mc/bnf/current/41001i222.htm), so possibly a small scraping flaw.  I suspect it is possible to work out pages that aren't real results if the dict retrieved from the json doesn't have name key.  Will test.

**Comment by davidmiller** [comment]
This was fixed by @rossjones in #7

Deployment follows shortly.
